config/routes.rb
Rails.application.routes.draw do
	root 'static_pages#test'
  get 'static_pages/myimages'
  get 'static_pages/test'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	require 'flickraw'
	def myimages
		@me = flickr.people.getInfo(user_id: "163585955@N03")

		@user = flickr.people.findByEmail(:find_email => 'torreyhogan@yahoo.com')
		info = flickr.photos.getInfo(:photo_id => "3839885270")
		@info = FlickRaw.url_profile(info) # => "https://www.flickr.com/people/41650587@N02/"
	end


	def test
		if params[:user_id]
			results = flickr.people.getPublicPhotos(user_id: params[:user_id])
			@photos = results.map {|x| FlickRaw.url_b(x) }
		end
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/myimages.html.erb
<%= @me.id %>

<%= @user.id %>
<%= @user.username %>
<%= @info %>

app/views/static_pages/test.html.erb
<h1>Display Flickr User Photos</h1>

<div>
	<%= form_tag(static_pages_test_path, method: "get") do%>
		<%= label_tag(:user_id) %>
		<%= text_field_tag(:user_id) %>

		<%= submit_tag("Search") %>
	<% end %>
</div>

<% if @photos != nil %>
	<% @photos.each do |photo| %>
		<img src= <%= photo %> height=200px >
	<% end %>
<% end %>